### ISSUE TITLE
Can't allocate memory with more than 2mb alignment

### ISSUE THREAD

**Issue by XiangpengHao** [purpleprotocol/mimalloc_rust#82] opened 2022-06-27 20:35 UTC
It seems that this crate can't allocate memory with more than 2mb alignment. Not sure if this error is from mimalloc itself or somewhere else.

To reproduce
```rust
use mimalloc::MiMalloc;

#[global_allocator]
static GLOBAL: MiMalloc = MiMalloc;

#[cfg(test)]
mod tests {

    #[test]
    fn wont_work() {
        let alloc_size = 2 * 1024 * 1024;
        let layout = std::alloc::Layout::from_size_align(alloc_size, alloc_size).unwrap();
        let alloc = unsafe { std::alloc::alloc_zeroed(layout) };
        assert!(!alloc.is_null());
    }

    #[test]
    fn it_works() {
        let alloc_size = 2 * 1024 * 1024;
        let layout = std::alloc::Layout::from_size_align(alloc_size, alloc_size / 2).unwrap();
        let alloc = unsafe { std::alloc::alloc_zeroed(layout) };
        assert!(!alloc.is_null());
    }
}


```

**Comment by nathaniel-daniel** [comment] 2023-09-12 01:50
I think this was fixed with https://github.com/purpleprotocol/mimalloc_rust/commit/3a94859e21e6dcaa78684f6bcc57e5d8252b63df, I can't reproduce this after that commit.

**Closed** 2023-09-12 13:20 UTC
